import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Layout.module.css";
import { useDispatch, useSelector } from "react-redux";
import Link from "next/link";
import { useRouter } from "next/router";
import { artistLogOut } from "@/reducers/artist";
import Image from "next/image";

export default function Layout({ children }) {
  const router = useRouter();
  const dispatch = useDispatch();
  const artist = useSelector((state) => state.artist.value);

  const handleLogOut = () => {
    dispatch(artistLogOut());
    router.push("/");
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.main}>
        <div className={styles.sideMenu}>
          <div className={styles.logoContainer}>
            <Image
              className={styles.logo}
              src="/assets/logo.png"
              width={200}
              height={200}
            />
            <h2 className={styles.logoName}><span>Bar</span>Tist</h2>
          </div>
          <div className={styles.links}>
            <Link
              className={
                router.pathname === "/Events"
                  ? styles.selected
                  : styles.menuItem
              }
              href="/Events"
            >
              Mes évènements
            </Link>
            <Link
              className={
                router.pathname === "/Search"
                  ? styles.selected
                  : styles.menuItem
              }
              href="/Search"
            >
              Chercher des évènements
            </Link>
            <Link
              className={
                router.pathname === "/Propositions"
                  ? styles.selected
                  : styles.menuItem
              }
              href="/Propositions"
            >
              Mes propositions
            </Link>
          </div>
          <div>
            <div></div>
          </div>
          <button onClick={() => handleLogOut()}>Log out</button>
        </div>
        <div className={styles.center}>
          <div className={styles.header}>
            <button className={styles.button}>Create Event</button>
            <div className={styles.rightContent}>
              <div className={styles.imgContainer}></div>
              <div className={styles.userInfo}>
                <p className={styles.name}>{artist.pseudo}</p>
              </div>
            </div>
          </div>
          <div className={styles.content}>{children}</div>
        </div>
      </div>
    </>
  );
}
