import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Dashboard.module.css";
import { useSelector } from "react-redux";
const inter = Inter({ subsets: ["latin"] });



export default function Layout({children}) {

  const artist = useSelector((state) => state.artist.value);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.main}>
        <div className={styles.sideMenu}>
            <h2>BarTist</h2>
            <div className={styles.links}>
                <a>Mes events Prévus</a>
                <a>Chercher des events</a>
                <a>Mes propositions</a>
            </div>
            <div>
                <div></div>
            </div>
            <button >Log out</button>
        </div>
        <div className={styles.center}>
          <div className={styles.header}>
            <button className={styles.button}>Create Event</button>
            <div className={styles.rightContent}>
                <div className={styles.imgContainer}></div>
                <div className={styles.userInfo}>
                    <p className={styles.name}>{artist.pseudo}</p>
                </div>
            </div>
          </div>
          <div className={styles.content}>
            {children}
          </div>
        </div>
      </div>
    </>
  );
}
